### ISSUE TITLE
Implement ERC-7496: NFT Dynamic Traits as a component in Cairo 2.6 

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-7496#1]
**Description**
---
Implement [EIP-7496: NFT Dynamic Traits](https://eips.ethereum.org/EIPS/eip-7496) in Cairo 2.6 based on the [Solidity Reference Implementation](https://github.com/ethereum/ERCs/tree/master/assets/erc-7496)

**Additional Information**
---------------------------
[Easy  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] Implementation of a component-based EIP-7496

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by stevencartavia** [comment]
Hi, I can get this

**Comment by raizo07** [comment]
Hello, if this is still open, can I get it?

**Comment by TAdev0** [comment]
@raizo07  are you working on it? Otherwise i can do this tonight @tekkac
