### ISSUE TITLE
Implement Starknet Foundry Integration tests

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-7496#3]
**Description**
---
Adapt and implement integration tests using Starknet Foundry in Cairo 2.6 from the [ERC specification implementation](https://github.com/ethereum/ERCs/tree/master/assets/erc-7496).

**Additional Information**
---------------------------
[Medium Difficult  - Cairo - Medium Priority]

**Acceptance Criteria**
---
- [ ] Add the Starknet Foundry dependency
- [ ] Adapt and pass integration tests from the Solidity implementation of [EIP-7496](https://eips.ethereum.org/EIPS/eip-7496)

**Comment by JimmyFate** [comment]
Hey :)
Can I hop on this?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by Joy-Adah** [comment]
Hi @Khyati729 I'd love to work on this

**Comment by Khyati729** [comment]
> Hi @Khyati729 I'd love to work on this

hey, we are just assigning 1 issue person person. Once you are done with your initial committed issue, please let me know and will assign this to you.

**Comment by Joy-Adah** [comment]
Okay. Thanks!

**Comment by saimeunt** [comment]
Can I try this please? @Khyati729
